components/edit-assistant.vue
server/routes/v1/assistants/[assistant]/index.put.ts
server/routes/v1/assistants/index.post.ts
server/routes/v1/assistants/index.ts
server/routes/v1/threads/index.ts
server/routes/v1/tools/[tool]/index.delete.ts
server/routes/v1/tools/[tool]/index.put.ts
server/routes/v1/tools/[tool]/index.ts
server/routes/v1/tools/index.post.ts
server/routes/v1/tools/index.ts

This change removes the /v1/rubra and /v1/rubra/x endpoints, and combines the assistant tools and gptscript_tools field for a simpler API experience.

chore: remove rubra API endpoints and combine assistant tools

---

tool.gpt

Get the local operating system using the official context tool and remove instructions to strip the file suffix from input. The latter will be handled in `gptscript` when the `--ui` option is provided.
Depends on https://github.com/gptscript-ai/gptscript/pull/530

fix: get os from context tool

---

components/script.tsx
components/script/chatBar.tsx
components/script/useChatSocket.tsx
server.mjs

This adds interrupt functionality to runs. Now when a script is generating something the "send" button will turn into a "stop button". The previously sent message will be removed from the chat history but you will be able to continue chatting with the bot.

feat: add interrupting for the LLM

---

tool.gpt

Should address https://github.com/gptscript-ai/gptscript/issues/560

fix: use xdg-open on linux

---

.gitignore
actions/scripts/fetch.tsx
actions/scripts/new.tsx
actions/threads.tsx
actions/upload.tsx
app/api/file/[name]/[tool]/route.ts
app/api/file/[name]/route.ts
app/api/file/route.ts
config/env.ts
server.mjs

Ensure the WORKSPACE_DIR and SCRIPTS_PATH directories are created before attempting to use them and refactor some misc related code.

fix: ensure app dirs exist 

---

package-lock.json
package.json
tool.gpt

Add a postinstall script to ensure the production NextJS build is generated on `npm install`. This enables `gptscript --ui` to run production UI builds.

enhance: run production builds for ui tool on npm install

---

config/env.ts
electron/main.mjs
package-lock.json
package.json
server/app.mjs

- Get the `WORKSPACE_DIR` env var instead of `GPTSCRIPT_WORKSPACE_DIR` (the former is set by the electron app at startup)
- Store threads and workspaces in the data dir instead of the cache dir
- Bump node-gptscript to v0.9.4
- Hardcode disable cache as stopgap for https://github.com/gptscript-ai/gptscript/issues/713

fix: set workspace dir from correct env var

---

.github/workflows/release.yml
electron/build.mjs

- Allow publishing to releases that are more than 2 hours old
- Ensure builds are published to non-draft releases

chore: ignore release time when publishing electron builds

---

components/script/useChatSocket.tsx

Providers only output their address, so it is not relavent to show to the user. This change ignores provider outputs unless the provider errors.

fix: ignore provider outputs unless an error occurs

---

server/app.mjs

I tested this locally with an interval of 30s and it works the way it should. I set the interval here to 30m. Let me know if it should be different.
Sorry for all the random whitespace changes, lol. I guess my WebStorm settings caused that.

pull gateway config from GitHub

---

server/app.mjs

When tools are added or removed, the socket server runs the script to
regenerate tool definitions. Now that the gateway-provider has been
incorporated as the default model provider, this logic gets stuck
waiting for user confirmation, and leads to the user getting stuck on a
loading screen. This same logic also means that if the LLM attempts to
call any other tool -- which it's prone to doing without being asked to --
we run into the same problem (e.g. the second tool add hangs forever
bug).
To fix this, add a handler to the tool run that auto-approves providers
and auto-denies requests to run any other tool.
Addresses https://github.com/gptscript-ai/gptscript/issues/761

fix: auto allow/deny tool run requests on dynamic tool add/remove

---

.github/workflows/release.yml
actions/auth/auth.tsx
electron/build.mjs
electron/main.mjs
package-lock.json
package.json
server/app.mjs

- **chore: add windows builds to releases**
- **fix: add metadata to gateway creds tool to pull tool runtimes**
TODO: bump node-gptscript when a new release is out

chore: add electron releases for windows

---

components/script/useChatSocket.tsx
contexts/script.tsx

This PR fixes an issue where socket's event emitter will be lost once socket is reconnected. This happens when app lost network connection, causing socket to reconnect but the server socket is reconnected and lose all the event listener including user-message. This causes an issue where typing user message doesn't trigger anything in UI.
Added the functionality to manually trigger the `run` event through the socket to re-add all the custom event listeners.

Fix socket reconnect issue that event emitter is lost

---

server/app.mjs

Once tools have been added by thread states, restarting thread will lose them. This changes so that when thread is loaded, the tool is added from state.json.

Load tools that have been added by thread states

---

config/env.ts
electron/main.mjs
package-lock.json

Other pieces of the stack use GPTSCRIPT_GATEWAY_URL. This change adjusts it here for consistency.

chore: use GPTSCRIPT_GATEWAY_URL

---

components/script.tsx
components/script/chatBar/upload/workspace.tsx
contexts/script.tsx
package-lock.json

This PR should fix all the bugs where workspace and restart is behaving weird when thread is created on the fly.
The issue is that when thread is created on the first user message, thread is not set. This is causing multiple unexpected behavior where managing workspace and restart relies on thread variable.
https://github.com/gptscript-ai/gptscript/issues/724
https://github.com/gptscript-ai/gptscript/issues/771
https://github.com/gptscript-ai/gptscript/issues/743

Fix thread bug where thread is not set when created on the fly

---

actions/threads.tsx
components/script.tsx
components/script/chatBar/upload/workspace.tsx

There is an issue where workspace is changed before thread gets created. The changed workspace is not passed into thread when it is getting created. This PR changes so that the workspace that user changed will get persisted into the thread when it gets created.
https://github.com/gptscript-ai/gptscript/issues/743

Fix workspace not being set when thread is first created.

---

actions/me/scripts.tsx
app/explore/page.tsx
components/edit/configure.tsx
components/edit/configure/customTool.tsx
components/edit/configure/imports.tsx
components/edit/configure/imports/toolCatalog.tsx
contexts/edit.tsx

Doing a few things here.
1. Fixed an issue with private custom tools not running
2. Updated the avatar on the edit page to be text instead of a plus icon.
3. Updating the explore page to be more functional and have a featured section by default
4. Updated the tool catalog styling a bit to reflect the new explore page a bit

feat: update explore page, fixing private custom tools, and update tool catalog styling

---

package-lock.json
package.json

Prep for the `v0.10.0-rc2` pre-release by bumping node-gptscript and desktop's package version.

chore: bump node-gptscript to v0.9.5-rc2 and desktop's package version

---

components/scripts/create.tsx
contexts/edit.tsx

Need to use `replaceAll` to replace slug with space.

Fix: use ReplaceAll to replace space when contructing slug

---

components/script.tsx
contexts/script.tsx

This PR tweaks the assistant title in front of message, and also give default assistant name to tidly.

Fix: Tweak assistant title style, set default assistant

---

electron/main.mjs

If the app is being started for the first time, the workspace directory doesn't exist, so startup will fail with an error. To fix this, ensure the workspace directory is created at startup.

fix: create workspace dir before browsersettings.json

---

components/threads.tsx
contexts/script.tsx
package-lock.json

for #161
The issue linked above was happening whenever the user switches from a Claude thread back to a normal gpt-4o. I figured out that this is just one case of a broader bug in the code, where switching threads can cause the previously selected script to execute.
The script context has a `script` and `scriptContent` state, the latter taking priority over the former. The thread code was overwriting `script` but doing nothing to `scriptContent`, which was the source of the issue here.

fix: erase script content when switching threads

---

components/edit/configure.tsx

This adds a finish button when creating/editing assistant that takes you back to the assistance page.
https://github.com/gptscript-ai/desktop/issues/117

Feat: Add finish button when creating or editing assistant

---

app/error.tsx
contexts/script.tsx
electron/config.mjs
electron/main.mjs
electron/preload.mjs
package-lock.json
package.json
server.mjs
server/app.mjs

Capture the combined log output from both client and server side and write them to the console and a log file (at `~/Library/Logs/acorn/acorn.log` on MacOS).
Log files are rotated at 1 MB.
Notes:
- This is the simpler of two approaches I'd played with, [the other](https://github.com/njhale/desktop/commit/4c022192888999cd241a4d3194c6ab5d85f92c75#diff-964ef2320b4c8d24957141cb9d4fa240c0c58871774b924aa2090eef2879dccd) had more control over the log formats -- e.g. color, json output, etc -- and log rotation, but was more complex and had some issues capturing everything.
- For logging to be an effective means to debug, we're going to want to instrument more of the business logic -- e.g. the socket server -- with debug logs. Be on the look out for a PR in the near future adding this.
- Long …

feat: write combined server and client logs to the console and a file

---

electron/config.mjs

The log rotation is broken such that when the current log file reaches 1 MB, a ton of
errors are generated by electron-log, which causes the file size to balloon in a bad way.
Fix it by correcting the type passed when renaming the old log file.

fix: pass correct type in rotation logic

---

server/app.mjs

We were accidentally giving the LLM the ability to call credential tools when we took this approach to dynamic tool adding. This PR fixes it by filtering out all of the credential tools before giving them to the LLM.

fix: remove credential tools from dynamically added tools

---

components/script/messages.tsx
components/script/messages/confirmForm.tsx
components/script/useChatSocket.tsx

For #185 and gptscript-ai/gptscript#702

enhance: openapi: better confirmation prompts

---

.gitignore
actions/knowledge/knowledge.ts
actions/threads.tsx
actions/upload.tsx
app/edit/page.tsx
app/page.tsx
components/edit/configure/customTool.tsx
components/script.tsx
components/script/chatBar.tsx
components/script/chatBar/commands.tsx
components/threads/new.tsx
contexts/script.tsx
electron/build.mjs
electron/config.mjs
electron/main.mjs
package-lock.json
package.json
scripts/install-binary.mjs
server/app.mjs

This pr adds the following features/changes/improvements:
1. Add new knowledge ingestion workflow. It ingests file using threadID as datasetID after file is uploaded. It also packages latest knowledge binary releases into the app. It also adds new `GPTSCRIPT_THREAD_ID` to gptscript run so that it can be used by knowledge tool to know which dataset it needs to query from.
2. It changes thread to have its unique workspace. For knowledge files, it will be stored in `knowledge` subdir inside its own workspace.
3. Changed so that when you go to chat, if there is no thread, it will automatically create a thread with tildy. Once you have threads, it will go to the latest thread you interacted with.
4. Make so that loading status is moved to message bar/button instead of whole screen.
5. Chatting …

Feat: Use thread unique workspace, add knowledge ingest

---

server/app.mjs

Since the tool parameter is passed here as a string and the former for-loop used tool as a Tool object, this caused the tool that was saved in the thread state to be an object rather than a string. This would cause errors when reloading the thread from the file.

fix: add tool to thread state as a string

---

components/threads/new.tsx

Get rid of divider on the last section.

Fix: small tweak to not show divider after the last section

---

components/script/chatBar/commands.tsx
components/script/useChatSocket.tsx
package-lock.json
package.json
server/app.mjs

Before this change, the chat icon would change based on the tool that was being called. For example, if an assistant was using a tool that needed to prompt the user, then the icon would change to the initials for that tool. After this change, the icon will only change when the assistant changes.
A side effect that is also addressed in this change: restoring a thread now has the correct icons for the messages. This will only be true for threads created after this change.

fix: stop changing icon during chat

---

server/app.mjs

If the user stopped the response, then the responding tool will not be defined because no tool responded.

fix: allow recovery when the user stops response

---

components/script/chatBar/commands.tsx

This fixes an issue where toolModal is not closed after adding a tool through command bar.

Fix: Close tool modal after tool is added

---

components/threads/menu.tsx

This PR fixed an issue where user can't update thread name
[#113](https://github.com/gptscript-ai/desktop/issues/113)

Fix: use modal to rename threads

---

contexts/script.tsx

If the ScriptContext gets rendered twice, we have to use Ref to prevent socket being run twice. 
https://github.com/gptscript-ai/desktop/issues/226

Fix: Use ref to prevent accidentally double-run when re-render

---

server/app.mjs

The tool is getting added to the block's tool list. So, it must also be removed from this list.

fix: remove a dynamically added tool from an assistant

---

actions/gptscript.tsx
components/edit/configure/imports.tsx
contexts/edit.tsx
electron/main.mjs

Fix the imported tools section of the edit page by:
- Loading remote tools to get the correct display names
- Using the full remote tool refs to select icons
This ensures tools get display names and icons that match the ones
used in the tool catalog.

fix: imported tool names and icons on edit page

---

components/chat/chatBar/commands.tsx
components/chat/chatBar/toolCatalog.tsx
components/edit/configure/imports.tsx
components/edit/configure/imports/toolCatalog.tsx
components/edit/configure/imports/toolCatalogModal.tsx

Don't allow tools to be removed from an assistant from the catalog
modal. Also, ensure the modal closes after selecting a tool to add.

enhance: don't allow tools to be removed from the catalog modal

---

components/scripts/knowledge-dropdown.tsx
components/scripts/tool-dropdown.tsx

In the corresponding dropdowns, this change adjusts the text color for "No Tools" and "No Knowledge" to be lighter.

chore: change text color for no tools/knowledge

---

components/chat.tsx
components/chat/chatBar.tsx
components/scripts/knowledge-dropdown.tsx
components/scripts/script-save.tsx
components/scripts/tool-dropdown.tsx
contexts/chat.tsx
server/app.mjs

If a user has added tools to a thread, then they will be able to save the assistant such that these tools become part of the assistant. The only exception to this is the knowledge tool: the user can't explicitly add the knowledge tool, so it will not be saved to the assistant. This will change when a user has the ability to add knowledge to an assistant.

feat: add ability to save an assistant

---

server/app.mjs

When switching threads, the socket will send back the messages and tools for the thread. However, if the thread state file doesn't exist yet, nothing is sent. This leads to the tools being leftover from the previous thread.
This change will emit the event so that the tools are correctly set for a new thread.

fix: clear tools when new thread is created

---

actions/gptscript.tsx
components/chat.tsx
components/chat/chatBar.tsx
components/chat/useChatSocket.tsx
components/scripts/knowledge-dropdown.tsx
components/scripts/script-save.tsx
components/scripts/tool-dropdown.tsx
components/threads.tsx
contexts/chat.tsx
server/app.mjs

A change has been merged into gptscript core that allows us to simplify the dynamic tool logic.

enhance: simplify the dynamic tool logic

---

actions/knowledge/filehelper.ts
actions/knowledge/knowledge.ts
components/edit/configure.tsx
components/edit/configure/imports.tsx
components/knowledge/KnowledgeModals.tsx
components/scripts.tsx
config/env.ts
contexts/edit.tsx

Note that this will have to be rebased once donnie's change is out.
The Server side implemetation:
1. For each assistant, we store all the files into ${DefaultWorkspace}/knowledge/{script_data}/{id}/data.
2. Once file is added, we copy the files over and run ingest with scriptID as dataset.
3. A knowledge tool will also be added into the script to run retrieval with the same scriptID.

Feat: Add knowledge first class support in Assistant

---

contexts/chat.tsx

scriptDisplayName is likely to be empty when we create thread so just use empty name as the thread name will be named as `New Thread X`. It is going to be renamed anyway after user type first message.
https://github.com/gptscript-ai/desktop/issues/340

Fix: just use the scriptDisplayName

---

contexts/edit.tsx

This should fix the bug 
```
2024-08-29T05:47:14.205Z [server] [ERROR]  ⨯ unhandledRejection: TypeError: Cannot read properties of undefined (reading 'digest')
at /Users/daishan/work/ui/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:36:17710
at AsyncLocalStorage.run (node:async_hooks:346:14)
at eL (/Users/daishan/work/ui/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:273726)
at /Users/daishan/work/ui/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:269554
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-08-29T05:47:14.206Z [server] [ERROR]  ⨯ unhandledRejection: TypeError: Cannot read properties of undefined (reading 'digest')
at /Users/daishan/work/ui/node_modules/next/dist/compiled/next-s …
```

Fix: fix mysterious digest error bug

---

actions/knowledge/knowledge.ts
components/edit/configure.tsx
components/knowledge/KnowledgeModals.tsx
components/scripts/tool-dropdown.tsx
contexts/edit.tsx

This PR revamps knowledge UX in assistant page, also added some error handling.
https://github.com/gptscript-ai/desktop/issues/335

Fix: revamp knowledge UX based on feedback

---

components/chat/chatBar.tsx

This fixed an issue where you type ArrowUp and cursor is not moving to the right.

Fix: cursor not going to the right after going to previous message

---

actions/knowledge/knowledge.ts
actions/threads.tsx
actions/upload.tsx
components/threads/menu.tsx

This PR moves thread to {Thread_location}/${id}/knowledge to separate workspace from it per ask for craig. Also deletes the dataset when thread is deleted.

Fix: Move knowledge location for thread, delete dataset after thread deletion

---

actions/gptscript.tsx
actions/helpers.ts
components/chat.tsx
components/chat/chatBar.tsx
components/chat/chatBar/commands.tsx
components/chat/chatBar/search/catalog.tsx
components/edit/configure/imports.tsx
components/edit/configure/imports/toolCatalog.tsx
hooks/useDebounce.ts
hooks/useFetch.ts
hooks/useLogEffect.ts
model/tools.ts
package-lock.json
package.json

This PR enhances the inline tool catalog
- Shrinks tool icons to make items more compact
- adds query to fetch tools from api and append them to list
- improves focus logic to always forward necessary keystrokes to chat input
- removes cli tools from featured tools list

Enhance: Add external tools from query to tool catalog

---

actions/gptscript.tsx
components/scripts.tsx
components/scripts/script-save.tsx
contexts/edit.tsx
server/app.mjs

Now that tools can have different types, checking for type "tool" is not correct. Instead, check for type being not text.

chore: check for "not text" instead of "tool"

---

components/chat.tsx
components/chat/chatBar.tsx
components/chat/useChatSocket.tsx
contexts/chat.tsx

If the application is waiting for a prompt response (either prompt or confirmation), then this change will disable the chat input and use a placeholder to indicate that the application is waiting for a response.

fix: disable chat input any time we are waiting for a prompt response

---

components/chat/chatBar/commands.tsx
components/chat/chatBar/upload/workspace.tsx
components/chat/useChatSocket.tsx
components/scripts/knowledge-dropdown.tsx
components/scripts/script-save.tsx
components/threads.tsx
contexts/chat.tsx
server/app.mjs

This change will ensure that currently running gptscript runs are stopped when switching threads. Additionally, this change removes the redundant selectedThreadId state because it is the same as thread.
Finally, we stop displaying the "run aborted" errors to the user because it isn't really an error: the user has chosen to abort the run.

fix: ensure that runs are stopped when switch threads

---

components/threads.tsx

This change was added to try to speed up the UI switch from one thread to the next. However, it seems to be causing issues with running messages bleeding over to other threads.

fix: stop resetting the messages when the thread changes

---

components/chat/useChatSocket.tsx

If a tool call starts with get, list, or read and is from our github
org, then auto-approve it.
Signed-off-by: Craig Jellick <craig@acorn.io>

Enhance: Allow all "read" calls from our tools

---

components/chat/chatBar.tsx
server/app.mjs

When adding files through Tildy, there is no script id so make sure it always gets set. Knowledge requires both environmental variables to be set.
https://github.com/gptscript-ai/desktop/issues/421

Fix: make sure script id is always set

---

components/chat.tsx
components/chat/useChatSocket.tsx

Fixing this issue by adding an immediate temporary message whenever a user sends a message. This give the illusion that we're responding faster but really we're just adding an empty message immediately.
The result looks something like this.
https://github.com/user-attachments/assets/a8d5dac9-d0d2-433b-882d-c876269bfbb5

fix: add immediate temp response when user sends a message

---

components/edit/configure.tsx

https://github.com/gptscript-ai/desktop/issues/408

feat: move dynamic instructions into the advanced section for editing

---

contexts/chat.tsx

If this is not reset, then the tools from the previous selected thread will be leftover, but not actually available to the thread.

fix: reset tools when creating a thread

---

actions/browser.tsx
app/settings/page.tsx
electron/config.mjs
electron/main.mjs

feat: browser settings in the settings page

---

actions/knowledge/util.ts
scripts/install-binary.mjs

* fix: queryrelevancy prompt by @iwilltry42 in https://github.com/gptscript-ai/knowledge/pull/104
* fix: debug mode flag + bm25 silence no docs err + keepMin option for threshold post-processor by @iwilltry42 in https://github.com/gptscript-ai/knowledge/pull/105
* fix: do not min/max-normalize already normalized similarity scores to not distort them by @iwilltry42 in https://github.com/gptscript-ai/knowledge/pull/107
* change: bump chromem-go fork dep to include openai embedding retries by @iwilltry42 in https://github.com/gptscript-ai/knowledge/pull/108
Ref https://github.com/gptscript-ai/desktop/issues/425 & https://github.com/gptscript-ai/desktop/issues/264 & https://github.com/gptscript-ai/desktop/issues/275

change: upgrade knowledge to v0.4.13 to include fixes

---

components/chat.tsx
components/chat/messages.tsx
components/chat/messages/confirmForm.tsx
components/chat/useChatSocket.tsx
contexts/chat.tsx
server/app.mjs

- **fix: stop OOM on long messages**
- **fix: use workqueue to offload progress events**
Addresses: #403

fix: oom on long messages

---

components/scripts/script-save.tsx

When a user uses the "Save Assistant As" functionality, the new assistant they are creating is supposed to replace the current assistant in the thread. This was happening correctly.
However, the threads were being stored in state. Therefore, navigating away from the thread and coming back to it would make it look like the old assistant was still being used. This change will refresh the thread state after "Save Assistant As" so that the state will reflect the new assistant.

fix: fetch threads after using "Save As" on a thread

---

components/chat.tsx
components/chat/messages/confirmForm.tsx
components/chat/messages/promptForm.tsx
components/chat/useChatSocket.tsx
contexts/chat.tsx

When a prompt was followed by another prompt, React was "helping" us by not completing resetting the state. This caused an issue where the old state would be used in the next prompt, making it appear as though the prompt was already submitted.
This change will reset this state so it will not be reused.
This change also includes some small changes around what is displayed before and after prompts. For example, when an authentication prompt disappeared, the message would still say,
"<Tool> needs to authenticate ." Now, the message will switch back to "Waiting for model response..."

fix: improve multiple prompts

---

contexts/chat.tsx

We need to make that before running thread, threadID is always set. Otherwise this will break thread knowledge functionality as it relies on query thread knowledge dataset based on threadID.
https://github.com/gptscript-ai/desktop/issues/425
https://github.com/gptscript-ai/desktop/issues/420

Fix: Make sure thread id is set before run

---

components/chat.tsx
components/chat/chatBar.tsx
components/edit/configure.tsx
components/edit/configure/customTool.tsx
components/edit/configure/params.tsx

This fixes a few things relating to how setting parameters for sub tools work. It removed the "plus" button as well as the "enter" keybinding for new params. Instead, there is a new button to add params. This improves the UX since many users were getting confused why their params were not automatically persisting.
There was another confusing issue where tools without chat would have the chat bar enabled. This has been addressed and looks like the following.
There is a third issue here where the running of this tool does not actually requests the user to input their parameters. This will be fixed in a follow-up to minimize the size of this PR. That change will take some work.
#413

fix: address issues with how parameters work for subtools

---

actions/appSettings.tsx
app/settings/page.tsx
electron/main.mjs
server/app.mjs

There were some issues that were not caught in the last PR because a lot of the reviewers already had settings files. I didn't catch it while programming the settings page up for the same reason, to fix this this PR does 3 things.
1. The socket server now will use default settings if the settings file does not exist. This shouldn't happen, but just in case. This was an issue because of...
2. Create the settings.json file in the correct place, it was previously in the workspace dir which was incorrect. We now also only create it if it doesn't already exist.
3. Fixes an issue where the users could not set browser settings persistently. (noticed while fixing the root issue, but was not a cause of the root issue).
#480
https://acorn-io.slack.com/archives/C03FU91U4SX/p1725985732395979

fix: fix app.mjs panic and create settings.json on startup

---

.eslintrc.json
actions/gptscript.tsx
actions/scripts/fetch.tsx
components/chat/chatBar/commands.tsx
components/edit/configure/imports.tsx

This skips the verification step for tools that start with `sys.` to allow them to be added to chats and assistants
I opted not to include a hard-coded whitelist of system tools so that we could add/remove them without having to make UI updates. The downside is that adding an invalid sys tool could cause errors. Happy to update this if necessary

Feat: Allow sys tools to be added by URL

---

components/chat/chatBar/upload/files.tsx
electron/main.mjs
electron/preload.mjs
types/window.d.ts

This uses Electron's IPC code to open system files through the UI. It is done through a listeners on in the `main.js` of electron and an emitter in the next js app. Once the emitted event is received with a file it is opened with the system default.
https://www.electronjs.org/docs/latest/tutorial/ipc for more info.
#322

feat: add the ability to open files from the UI

---

components/chat/useChatSocket.tsx

Prior the work queue wouldn't be cleared which would cause a race condition between the interrupt and the processing message in the queue.

fix: address issue where you would have to hit interrupt twice

---

components/chat/messages.tsx
electron/main.mjs

https://github.com/gptscript-ai/desktop/issues/280
The default url transform in our markdown library seems to be stripping out url with file://. This break our knowledge response when giving source link reference that points to files.

Fix: make sure source link is configured and open in external browser

---

actions/knowledge/knowledge.ts

Log ingestion error to app log. Today we already show it in UI with truncated text but we should show the full error in acorn.log.

Fix: log ingestion error to stdout

---

components/chat/messages/calls.tsx
components/chat/messages/calls/stackTrace.tsx
components/saveFile.tsx
electron/main.mjs
electron/preload.mjs
types/window.d.ts

This PR adds a new feature allowing users to download stack traces of messages. It uses electron API's to do this and uses native API's to interact with the default file system of the user's OS.
<details>
<summary> Demonstration </summary>
https://github.com/user-attachments/assets/136f6daa-e33f-4ed6-b971-24530f998ead
</details>
#471

feat: add download option for stack traces

---

app/page.tsx
components/chat.tsx
components/chat/chatBar/CatalogListBox.tsx
components/chat/chatBar/commands.tsx
components/chat/messages.tsx
components/edit/configure/imports.tsx
components/threads.tsx

Make the featured tool catalog more responsive in smaller viewports.
- Make it shrink with the window
- Make it scrollable
- Move to Tooltip instead of `absolute`-ly positioned div to fix z-index issues
- Prevents threads container from shrinking with viewport

fix: move featured tool catalog to tooltip + make scrollable for smaller viewports

---

actions/knowledge/knowledge.ts

Since knowledge tool will produce more status log now, we need to increase the buffer size so that it doesn't error out when ingesting a big set of documents. https://github.com/gptscript-ai/desktop/issues/491
Note: we could do it based on node stream, but not going to spend too much effort on this fix.

Fix: increase buffer size for knowledge ingest processFix
