package-lock.json, package.json
Signed-off-by: Craig Jellick <craig@acorn.io>
=> chore: bump for v0.8.2 release

package-lock.json, package.json
Signed-off-by: Craig Jellick <craig@acorn.io>
=> chore: bump for v0.8.3 release

components/script/useChatSocket.tsx, config/env.ts, package-lock.json, package.json, server/app.mjs
Initialize the gatewayURL and integrations config on startup.
=> enhance: bootstrap gateway and integrations config

actions/me/scripts.tsx
This should help with rate limits.
=> chore: enable caching when parsing tools

components/edit/configure/imports/toolCatalog.tsx, components/script/chatBar/commands.tsx
The new knowledge tool version will properly wire itself into the chat
context so that the assistant tries to call it.
=> Fix: Update knowledge tool

electron/main.mjs
=> set up browser settings to use headless mode

.dockerignore, actions/gptscript.tsx, actions/me/scripts.tsx, package-lock.json, package.json, server/app.mjs
- **enhance: use load method to add tools**
- **chore: bump node-gptscript to get load method**
Addresses #80
=> Use load method to add tools

components/edit/configure/imports/toolCatalog.tsx, components/script/chatBar/commands.tsx
...+ OpenAI OCR documentloader
=> chore: bump knowledge tag to include keyword-based prefiltering

components/script/useChatSocket.tsx
**Fix: Whitelist the oauth2 tool**
=> Fix: Whitelist the oauth2 tool

components/script/messages/promptForm.tsx, components/script/useChatSocket.tsx, package-lock.json, package.json, server/app.mjs
The OAuth tool prompt will now include metadata. When this metadata is detected, the GUI will handle the opening of the browser instead of the tool, for a more seamless UX.
=> feat: handle OAuth authentication flow

app/page.tsx, components/threads/new.tsx, config/assistant.ts
https://github.com/gptscript-ai/desktop/issues/219
=> Feat: New design for Add thread dropdown

components/script/chatBar.tsx
This PR adds the ability to use ArrowUp and ArrowDown to nagivate previous sent messages in chatbar.
=> Feat: Implement features to use arrowup and arrowdown to go to user message history

components/script/useChatSocket.tsx
We shouldn't prombt the user about these repos.
=> Enhance: Add a few more repos to the allowlist

components/threads.tsx
Pin Threads menu nav to the top of the menu container
Addresses #261
=> fix: chat list scroll scope

components/chat/chatBar.tsx
Updating as the messages are coming in causes issues with useEffect.
=> fix: update user messages only after response is complete

components/chat/useChatSocket.tsx, components/explore/scriptModal.tsx, components/threads.tsx, contexts/chat.tsx
https://github.com/gptscript-ai/desktop/issues/309
https://github.com/gptscript-ai/desktop/issues/226
=> Fix: fix thread restarting issues

components/edit/configure.tsx
The file table doesn't have max-height, this will cause issues when a lot of files get added
=> Fix: make sure files table has max-h

components/chat/chatBar/commands.tsx, components/chat/chatBar/search/catalog.tsx
Tool Catalog Fixes:
- close tool catalog after adding tool to assistant
- remove community tool search on tool catalog
- update filtering text on chatbar commands list
=> fix: Tool catalog enhancement bugfixes

actions/knowledge/knowledge.ts, actions/knowledge/util.ts, components/chat.tsx, components/edit/configure.tsx, components/scripts/script-save.tsx, components/scripts/tool-dropdown.tsx, contexts/chat.tsx, contexts/edit.tsx, electron/config.mjs, scripts/install-binary.mjs, server/app.mjs
This PR use the latest and greated context tool from @iwilltry42. It also removes the inline tool and replace it with the remote tool that is capable of querying data from both thread and script dataset.
=> Use latest knowledge context tool

components/chat/chatBar/commands.tsx
https://github.com/gptscript-ai/desktop/issues/383
=> Fix: fix workspace modal not showing up

actions/me/scripts.tsx, components/edit/scriptNav.tsx, components/scripts/create.tsx
Doing a slight refactor by adding a "newDefaultAssistant" and then using it. The issue itself has to do with not pushing to the correct URL when redirecting since it needs an ID.
https://github.com/gptscript-ai/desktop/issues/307
=> fix: address issue with assistant menu in editor

actions/knowledge/util.ts, scripts/install-binary.mjs
https://github.com/gptscript-ai/desktop/issues/456
=> chore: upgrade knowledge to v0.4.14-rc.2 to include embeddings retry logic fix

actions/knowledge/knowledge.ts
https://github.com/gptscript-ai/desktop/issues/457
=> Enhance: Print std adn stderr to desktop app for ingestion flow

components/chat/useChatSocket.tsx
Previously messages would get deleted on interrupt. This PR fixes that.
=> fix: do not delete message on interrupt

actions/knowledge/util.ts, scripts/install-binary.mjs
Release: https://github.com/gptscript-ai/knowledge/releases/tag/v0.4.14-rc.5
Issues:
https://github.com/gptscript-ai/desktop/issues/402
https://github.com/gptscript-ai/desktop/issues/336
=> chore: upgrade knowledge tool to have tool fix to properly parse the json output

actions/knowledge/util.ts, scripts/install-binary.mjs
Ref https://github.com/gptscript-ai/desktop/issues/491#issuecomment-2344823664
=> chore: upgrade knowledge to include OpenAI API retries fix

components/edit/configure.tsx
We should ingest files after syncing so that knowledge will automatically have updated content after syncing.
https://github.com/gptscript-ai/desktop/issues/517
=> Fix: ingest files after syncing

actions/knowledge/util.ts, scripts/install-binary.mjs
https://github.com/gptscript-ai/knowledge/compare/v0.4.14-rc.6...v0.4.14-rc.9
Potential blocker: https://acorn-io.slack.com/archives/C07FZ46QA2J/p1726748675162999?thread_ts=1726678637.072429&cid=C07FZ46QA2J
=> chore: knowledge -> v0.4.14-rc.11
